export const projectData = [
	{
		image: "/work/1.png",
		category: "FrontEnd",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/2.png",
		category: "FrontEnd",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/3.png",
		category: "FullStack",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/4.png",
		category: "BackEnd",
		name: "Nexa Website",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/1.png",
		category: "BackEnd",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/2.png",
		category: "FullStack",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
	{
		image: "/work/3.png",
		category: "FullStack",
		name: "Nexa Website",
		description: "Lorem ipsum dolor sit amet, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS", "Node.js", "MongoDB"],
	},
	{
		image: "/work/4.png",
		category: "BackEnd",
		name: "Nexa Website",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, elit arcu.",
		link: "/",
		github: "/",
		stack: ["React", "Next.js", "Tailwind CSS"],
	},
];
